# Generated by Django 5.0 on 2024-12-12 13:22

import accounts.utils.base
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('uid', models.UUIDField(default=accounts.utils.base.hex_code, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('established_on', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['uid', 'name'], name='accounts_un_uid_29a6a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uid', models.UUIDField(default=accounts.utils.base.hex_code, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('enrollment_date', models.DateField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university')),
            ],
            options={
                'verbose_name_plural': 'Students',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['uid', 'name'], name='accounts_st_uid_3f0639_idx')],
            },
        ),
    ]
