# Generated by Django 4.2.10 on 2024-12-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_university_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='established_on',
            new_name='established_year',
        ),
    ]
